apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-test.fullname" . }}
  labels:
    {{- include "k3s-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "k3s-test.selectorLabels" . | nindent 4 }}
